### PR TITLE
Massive overhaul. Fix broken websites, new websites

### PR DESCRIPTION
**Pull request by dot-mike**
This update fixes a lot of websites that has changed how they publish images internally (particularly Schibsted owned websites using CDN).

Also added support for VG + Aftenposten

### CODE REVIEW

**Comment by Ondkloss** [comment]
Thanks for your contribution! I'm not immediately able to do the review, but I'll try to squeeze it in asap!

**Comment by Ondkloss** [comment]
Thanks again! I merged in your contribution. I did a few edits afterwards, but just tiny stuff. Also I'm not sure how many patterns/websites/systems you tested against...? I fixed Polar Media (for Møre-Nytt) at least. Still assume there's a bit of changes patterns since I last updated this, but this is certainly an improvement! Thanks.

**Comment by dot-mike** [comment]
Glad to see the merge went through. I tested most sites that I changed / added and I'm I sure I tested Polaris Media but looks like I mixed that one up... Thanks!

**Comment by dot-mike** [comment]
Will you bump the addon release as-well? @Ondkloss  :)

**Comment by Ondkloss** [comment]
You mean the releases on Chrome/Firefox? I'll do a quick review of each site/ system before to make it as functional as possible for the release, then I'll deploy!

**Comment by Ondkloss** [comment]
@dot-mike I did a quick run through the different "systems". Moved a couple of things around, but overall very decent! I noticed you touched Newsflow (e.g. https://mre.no), and I think the URL now matches but I am no longer able to produce a large image from it. I see there is some potential using the `srcset`, but from pure URL it seems hard. Might have to look a bit more to get that working so I'll try to get a release going for the current state. Thanks again, and feel free to contribute further as I'll make sure to include any valuable additions :)

**Pull request merged**
